session_name: github_summary
start_directory: .
# shell_command_before:
#   - "[ -f .venv/bin/activate ] && source .venv/bin/activate && reset"
windows:
  - window_name: nvim
    layout: main-horizontal
    options:
      main-pane-height: 35
    panes:
      - window_name: empty
        layout: main-horizontal
        panes:
          - focus: true
  - window_name: schedule_run
    layout: main-horizontal
    options:
      main-pane-height: 35
    panes:
      - shell_command:
          - uv run github-summary web
