[project]
name = "github-summary"
version = "0.8"
description = "A CLI tool to summarize GitHub repository activity using LLMs."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic",
    "typer",
    "rich",
    "python-dotenv",
    "requests",
    "pytest",
    "toml",
    "openai",
    "ipdb",
    "feedgen",
    "schedule",
    "markdown-it-py",
    "tenacity",
]

[project.scripts]
github-summary = "github_summary.main:app"

[tool.setuptools]
packages = ["github_summary"]

[tool.ruff]
line-length = 120
indent-width = 4
lint.extend-select = ["I"]
